#!/bin/bash

datenow=`date +"%Y%m%d%H%M"`

bjobs -u all | awk '{ print $2 }' | sed -e 's/USER// ; s/scan-x//' | sort | uniq > /tmp/currentusers.txt

for user in `cat /tmp/currentusers.txt`
do
   echo $datenow, | tr -d '\n'
   adquery user -C $user 2>/dev/null | sed -e 's/med.harvard.edu\/PEOPLE\/// ; s/^:.*$// ; s/AFFILIATE\//AFFILIATE-/ ; s/STUDENT\//STUDENT-/ ; s/\//,/' |
   tr -d '\n' ; bjobs -r -u $user 2>/dev/null | 
   wc -l |
   awk '{ print "," $0 }'
done |
sort 
